services:
  - type: web
    name: justmemedia-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: RESEND_API_KEY
        sync: false
